In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
rest = pd.read_excel("dataset.xlsx" , sheet_name= "Restaurants")
orders = pd.read_excel("dataset.xlsx" , sheet_name= "Orders")
Customers = pd.read_excel("dataset.xlsx" , sheet_name= "Customers")
DateTable = pd.read_excel("dataset.xlsx" , sheet_name= "DateTable")

# Resturant Table Analysis

In [6]:
rest.head(2)

,RestaurantID,address,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,1,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,2,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari

In [7]:
rest.shape

(56250, 14)

In [8]:
rest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56250 entries, 0 to 56249
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   RestaurantID                 56250 non-null  int64
 1   address                      56235 non-null  object
 2   name                         56236 non-null  object
 3   online_order                 56234 non-null  object
 4   book_table                   56194 non-null  object
 5   rate                         48414 non-null  object
 6   votes                        56174 non-null  object
 7   location                     56128 non-null  object
 8   rest_type                    55914 non-null  object
 9   dish_liked                   28049 non-null  object
 10  cuisines                     56049 non-null  object
 11  approx_cost(for two people)  55745 non-null  object
 12  listed_in(type)              51655 non-null  object
 13  listed_in(city)              51626 non-null  object
dtypes: int64(1), object(13)
memory usage: 6.0+ MB

In [10]:
rest.isnull().sum()

RestaurantID                       0
address                           15
name                              14
online_order                      16
book_table                        56
rate                            7836
votes                             76
location                         122
rest_type                        336
dish_liked                     28201
cuisines                         201
approx_cost(for two people)      505
listed_in(type)                 4595
listed_in(city)                 4624
dtype: int64

In [33]:
rest["listed_in(type)"].value_counts().sort_values(ascending = False).head(5)

listed_in(type)
Delivery              24317
Dine-out              16253
Desserts               3379
Cafes                  1461
Drinks & nightlife      751
Name: count, dtype: int64

# Orders Table Analysis

In [36]:
orders.head()

,OrderID,RestaurantID,CustomerID,OrderDate,OrderValue,DeliveryTimeMins,OrderStatus,Quantity
0,1,32876,15443,2025-05-21,719,53,Delivered,4
1,2,3567,821,2023-04-08,1411,46,Delivered,1
2,3,49893,14072,2025-06-30,605,36,Delivered,1
3,4,43691,8141,2023-03-19,1118,20,Delivered,2
4,5,42789,1402,2024-07-11,271,30,Delivered,3

In [37]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   OrderID           200000 non-null  int64
 1   RestaurantID      200000 non-null  int64
 2   CustomerID        200000 non-null  int64
 3   OrderDate         200000 non-null  datetime64[ns]
 4   OrderValue        200000 non-null  int64
 5   DeliveryTimeMins  200000 non-null  int64
 6   OrderStatus       200000 non-null  object
 7   Quantity          200000 non-null  int64
dtypes: datetime64[ns](1), int64(6), object(1)
memory usage: 12.2+ MB

In [38]:
orders.shape

(200000, 8)

In [40]:
orders.describe()

,OrderID,RestaurantID,CustomerID,OrderDate,OrderValue,DeliveryTimeMins,Quantity
count,200000.000000,200000.000000,200000.000000,200000,200000.000000,200000.000000,200000.000000
mean,100000.500000,28162.152000,9997.414405,2024-05-14 04:18:28.368000256,824.572470,44.549740,2.500230
min,1.000000,1.000000,1.000000,2023-01-01 00:00:00,150.000000,20.000000,1.000000
25%,50000.750000,14091.000000,5021.000000,2023-09-07 00:00:00,488.000000,32.000000,2.000000
50%,100000.500000,28175.500000,9999.000000,2024-05-15 00:00:00,824.000000,45.000000,3.000000
75%,150000.250000,42240.000000,14969.000000,2025-01-19 00:00:00,1162.000000,57.000000,3.000000
max,200000.000000,56250.000000,20000.000000,2025-09-26 00:00:00,1499.000000,69.000000,4.000000
std,57735.171256,16239.800517,5762.421659,NaN,389.315374,14.427597,1.116958

In [41]:
orders.isnull().sum()

OrderID             0
RestaurantID        0
CustomerID          0
OrderDate           0
OrderValue          0
DeliveryTimeMins    0
OrderStatus         0
Quantity            0
dtype: int64

In [46]:
orders["OrderStatus"].value_counts()

OrderStatus
Delivered    160227
Cancelled     19947
Delayed       19826
Name: count, dtype: int64

# Customer Table Analysis

In [49]:
Customers.head()

   CustomerID CustomerName                   City SignupDate CustomerType
0           1   Customer_1         Residency Road 2023-02-10    Returning
1           2   Customer_2  Koramangala 7th Block 2023-04-18    Returning
2           3   Customer_3        Electronic City 2022-11-29          New
3           4   Customer_4                    BTM 2023-03-11    Returning
4           5   Customer_5  Koramangala 8th Block 2023-02-22          New

In [50]:
Customers.shape

(20000, 5)

In [51]:
Customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    20000 non-null  int64
 1   CustomerName  20000 non-null  object
 2   City          20000 non-null  object
 3   SignupDate    20000 non-null  datetime64[ns]
 4   CustomerType  20000 non-null  object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 781.4+ KB

In [52]:
Customers.isnull().sum()

CustomerID      0
CustomerName    0
City            0
SignupDate      0
CustomerType    0
dtype: int64

In [55]:
Customers["City"].value_counts().sort_values( ascending = False).head(10)

City
BTM                      1876
HSR                       913
Koramangala 5th Block     903
JP Nagar                  811
Whitefield                783
Indiranagar               743
Jayanagar                 703
Marathahalli              665
Bannerghatta Road         562
Koramangala 1st Block     457
Name: count, dtype: int64

In [57]:
Customers["CustomerType"].value_counts().sort_values( ascending = False).head()

CustomerType
New          9945
Returning    8052
Premium      2003
Name: count, dtype: int64

# Date Table

In [59]:
DateTable.head()

        Date  Year  MonthNo MonthName Quarter  Day
0 2023-01-01  2023        1       Jan      Q1    1
1 2023-01-02  2023        1       Jan      Q1    2
2 2023-01-03  2023        1       Jan      Q1    3
3 2023-01-04  2023        1       Jan      Q1    4
4 2023-01-05  2023        1       Jan      Q1    5

In [60]:
DateTable.shape

(1000, 6)

In [61]:
DateTable.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1000 non-null   datetime64[ns]
 1   Year       1000 non-null   int64
 2   MonthNo    1000 non-null   int64
 3   MonthName  1000 non-null   object
 4   Quarter    1000 non-null   object
 5   Day        1000 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 47.0+ KB

In [62]:
DateTable.describe()

                      Date         Year      MonthNo          Day
count                 1000  1000.000000  1000.000000  1000.000000
mean   2024-05-14 12:00:00  2023.904000     6.100000    15.672000
min    2023-01-01 00:00:00  2023.000000     1.000000     1.000000
25%    2023-09-07 18:00:00  2023.000000     3.000000     8.000000
50%    2024-05-14 12:00:00  2024.000000     6.000000    16.000000
75%    2025-01-19 06:00:00  2025.000000     9.000000    23.000000
max    2025-09-26 00:00:00  2025.000000    12.000000    31.000000
std                    NaN     0.790828     3.307407     8.780861

In [63]:
DateTable.isnull().sum()

Date         0
Year         0
MonthNo      0
MonthName    0
Quarter      0
Day          0
dtype: int64

In [70]:
DateTable["Year"].value_counts().sort_values()

Year
2025    269
2023    365
2024    366
Name: count, dtype: int64

In [68]:
DateTable["Quarter"].value_counts().sort_values()

Quarter
Q4    184
Q1    271
Q3    272
Q2    273
Name: count, dtype: int64

In [71]:
DateTable["MonthName"].value_counts().sort_values()

MonthName
Nov    60
Oct    62
Dec    62
Feb    85
Sep    86
Apr    90
Jun    90
Jan    93
Aug    93
Mar    93
Jul    93
May    93
Name: count, dtype: int64